### ISSUE TITLE
[question] source.scss to build.min.css

### ISSUE THREAD

**Issue by izenn** [ledowong/padopt#1]
what are you using to build the build.min.css?  I want to suggest a couple changes from my fork, however, it is pretty painful having to edit both the source.scss and build.min.css

**Comment by izenn** [comment]
nevermind -- i figured out how you were using gulp

**Comment by ledowong** [comment]
I have updated the README with more explanation. See if that help.
https://github.com/ledowong/padopt/commit/58c758c67ffe7f4724b05d5f38736847fe417e70
